#- name: loadbalancer.devops
#  ip: 192.168.34.30
#  cpus: 1
#  mem: 1024
#  os: ubuntu
#  docker: not_required
#  provisioner: shell
#  playbook: infrastructure/provisioning/loadbalancer/script.sh
#  size: 10GB
- name: registry.devops
  ip: 192.168.34.11
  cpus: 1
  mem: 512
  os: alpine
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/registry/playbook.yml
  size: 10GB
- name: staging.devops
  ip: 192.168.34.12
  cpus: 1
  mem: 1024
  os: ubuntu
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/staging/playbook.yml
  size: 10GB
- name: production.devops
  ip: 192.168.34.13
  cpus: 1
  mem: 1024
  os: ubuntu
  docker: required
  provisioner: ansible  
  playbook: infrastructure/provisioning/production/playbook.yml
  size: 10GB
- name: archiver.devops
  ip: 192.168.34.14
  cpus: 1
  mem: 256
  os: alpine
  docker: not_required
  provisioner: ansible  
  playbook: infrastructure/provisioning/archiver/playbook.yml
  size: 10GB
- name: mail.devops
  ip: 192.168.34.15
  cpus: 1
  mem: 256
  os: alpine
  docker: not_required
  provisioner: ansible
  playbook: infrastructure/provisioning/mail/playbook.yml
  size: 10GB
- name: jenkins.devops
  ip: 192.168.34.16
  cpus: 1
  mem: 2048
  os: ubuntu
  docker: not_required
  provisioner: ansible
  playbook: infrastructure/provisioning/jenkins/playbook.yml
  size: 20GB
- name: elastic.devops
  ip: 192.168.34.18
  cpus: 1
  mem: 2048
  os: ubuntu
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/elastic/playbook.yml
  size: 10GB
- name: logstash.devops
  ip: 192.168.34.20
  cpus: 1
  mem: 2048
  os: ubuntu
  docker: not_required
  provisioner: ansible  
  playbook: infrastructure/provisioning/logstash/playbook.yml
  size: 10GB
- name: kibana.devops
  ip: 192.168.34.19
  cpus: 1
  mem: 1024
  os: ubuntu
  docker: not_required
  provisioner: ansible
  playbook: infrastructure/provisioning/kibana/playbook.yml
  size: 10GB
- name: vault.devops
  ip: 192.168.34.17
  cpus: 1
  mem: 512
  os: ubuntu
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/vault/playbook.yml
  size: 10GB  